SanjyShopApplication/SanjyShop.UI/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanjyShop.UI.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult MenuList()
        {
            return View();
        }
    }
}

SanjyShopApplication/SanjyShop.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />*@
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>


        @RenderBody()
        <hr />
       


    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @*<script src="~/Scripts/bootstrap.min.js"></script>*@
    @RenderSection("Scripts", false)
</body>
</html>

SanjyShopApplication/SanjyShop.UI/Views/Shared/_LayoutMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="https://fonts.googleapis.com/css2?family=Reenie+Beanie&display=swap" rel="stylesheet">
    <link href="~/Content/assets/css/custom.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="adjust-nav">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="~/Content/assets/img/logo.png" />
                    </a>
                </div>

                <span class="logout-spn">
                    <h2>"Gateway To The Great Shopping..."</h2>
                </span>

                <!-- <span class="logout-spn" >
                    <button type="button" class="btn btn-warning">Logout</button>

                </span> -->
            </div>
        </div>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">


                    <li>
                        <a href="#"><i class="fa fa-archive"></i>Today's Orders</a>
                    </li>
                    <li>
                        <a href="@Url.Action("MenuList", "Menu", new { id = "" })"><i class="fa fa-table "></i>Today's Menu Lists</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-qrcode "></i>My Profile</a>
                    </li>
                    <li>
                        @if (Request.IsAuthenticated)
                        {
                            @Html.ActionLink("Logout", "Logout", "User", new { id = "" }, null);
                           // <a href="@Url.Action("Logout", "User", new { id = "" })">Logout</a>
                                @*@Url.Action("Logout", "User", new { id = "", Text = "Logout" }, null)
                                <a class="te" href="javascript:document.getElementById('logoutForm').submit()">Logout</a>*@


                                }
                        </li>
                </ul>
            </div>
        </nav>
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/custom.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>